name: Mailtutan

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Install Wasm32
      run: rustup target add wasm32-unknown-unknown

    - name: Install Clippy
      run: rustup component add clippy

    - name: Install trunk
      run: cargo install --locked trunk

    - name: Check Clipy
      run: cargo clippy

    - name: Build
      run: make all

    - name: Run tests
      run: cargo test --verbose
